export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT = "LOGOUT";

export const FORGOT_PASSWORD_WITH_EMAIL_REQUEST = 'FORGOT_PASSWORD_WITH_EMAIL_REQUEST'
export const FORGOT_PASSWORD_WITH_EMAIL_SUCCESS = 'FORGOT_PASSWORD_WITH_EMAIL_SUCCESS'
export const FORGOT_PASSWORD_WITH_EMAIL_FAILURE = 'FORGOT_PASSWORD_WITH_EMAIL_FAILURE'

export const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST"
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS"
export const CHANGE_PASSWORD_FAILURE = "CHANGE_PASSWORD_FAILURE"