export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const LOGOUT = "LOGOUT";

export const GET_ALL_ADDRESS_REQUEST = 'GET_ALL_ADDRESS_REQUEST'
export const GET_ALL_ADDRESS_SUCCESS = 'GET_ALL_ADDRESS_SUCCESS'
export const GET_ALL_ADDRESS_FAILURE = 'GET_ALL_ADDRESS_FAILURE'

export const CREATE_NEW_ADDRESS_REQUEST = 'CREATE_NEW_ADDRESS_REQUEST'
export const CREATE_NEW_ADDRESS_SUCCESS = 'CREATE_NEW_ADDRESS_SUCCESS'
export const CREATE_NEW_ADDRESS_FAILURE = 'CREATE_NEW_ADDRESS_FAILURE'

export const UPDATE_NEW_ADDRESS_REQUEST = 'UPDATE_NEW_ADDRESS_REQUEST'
export const UPDATE_NEW_ADDRESS_SUCCESS = 'UPDATE_NEW_ADDRESS_SUCCESS'
export const UPDATE_NEW_ADDRESS_FAILURE = 'UPDATE_NEW_ADDRESS_FAILURE'

export const DELETE_NEW_ADDRESS_REQUEST = 'DELETE_NEW_ADDRESS_REQUEST'
export const DELETE_NEW_ADDRESS_SUCCESS = 'DELETE_NEW_ADDRESS_SUCCESS'
export const DELETE_NEW_ADDRESS_FAILURE = 'DELETE_NEW_ADDRESS_FAILURE'

export const FORGOT_PASSWORD_WITH_EMAIL_REQUEST = 'FORGOT_PASSWORD_WITH_EMAIL_REQUEST'
export const FORGOT_PASSWORD_WITH_EMAIL_SUCCESS = 'FORGOT_PASSWORD_WITH_EMAIL_SUCCESS'
export const FORGOT_PASSWORD_WITH_EMAIL_FAILURE = 'FORGOT_PASSWORD_WITH_EMAIL_FAILURE'

export const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST"
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS"
export const CHANGE_PASSWORD_FAILURE = "CHANGE_PASSWORD_FAILURE"