export const GET_PRODUCTS_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCTS_FAILURE = "GET_PRODUCT_FAILURE";

export const GET_PRODUCTS_BY_FILTER_REQUEST = "GET_PRODUCT_BY_FILTER_REQUEST";
export const GET_PRODUCTS_BY_FILTER_SUCCESS = "GET_PRODUCT_BY_FILTER_SUCCESS";
export const GET_PRODUCTS_BY_FILTER_FAILURE = "GET_PRODUCT_BY_FILTER_FAILURE";

export const GET_ALL_BRAND_REQUEST = "GET_ALL_BRAND_REQUEST";
export const GET_ALL_BRAND_SUCCESS = "GET_ALL_BRAND_SUCCESS";
export const GET_ALL_BRAND_FAILURE = "GET_ALL_BRAND_FAILURE";

export const GET_ALL_COLOR_REQUEST = "GET_ALL_COLOR_REQUEST";
export const GET_ALL_COLOR_SUCCESS = "GET_ALL_COLOR_SUCCESS";
export const GET_ALL_COLOR_FAILURE = "GET_ALL_COLOR_FAILURE";

export const GET_ALL_CATEGORY_REQUEST = "GET_ALL_CATEGORY_REQUEST";
export const GET_ALL_CATEGORY_SUCCESS = "GET_ALL_CATEGORY_SUCCESS";
export const GET_ALL_CATEGORY_FAILURE = "GET_ALL_CATEGORY_FAILURE";

export const GET_SINGLE_PRODUCTS_REQUEST = "GET_SINGLE_PRODUCT_REQUEST";
export const GET_SINGLE_PRODUCTS_SUCCESS = "GET_SINGLE_PRODUCT_SUCCESS";
export const GET_SINGLE_PRODUCTS_FAILURE = "GET_SINGLE_PRODUCT_FAILURE";

export const GET_CATEGORY_COUNT_REQUEST = "GET_CATEGORY_COUNT_REQUEST";
export const GET_CATEGORY_COUNT_SUCCESS = "GET_CATEGORY_COUNT_SUCCESS";
export const GET_CATEGORY_COUNT_FAILURE = "GET_CATEGORY_COUNT_FAILURE";

export const GET_FAVORITE_LIST_REQUEST = 'GET_FAVORITE_LIST_REQUEST';
export const GET_FAVORITE_LIST_SUCCESS = 'GET_FAVORITE_LIST_SUCCESS'; 
export const GET_FAVORITE_LIST_FAILURE = 'GET_FAVORITE_LIST_FAILURE'; 

export const ADD_PRODUCT_TO_FAVORITE_LIST_REQUEST = 'ADD_PRODUCT_TO_FAVORITE_LIST_REQUEST';
export const ADD_PRODUCT_TO_FAVORITE_LIST_SUCCESS = 'ADD_PRODUCT_TO_FAVORITE_LIST_SUCCESS'; 
export const ADD_PRODUCT_TO_FAVORITE_LIST_FAILURE = 'ADD_PRODUCT_TO_FAVORITE_LIST_FAILURE'; 

export const DELETE_PRODUCT_FROM_FAVORITE_LIST_REQUEST = 'DELETE_PRODUCT_FROM_FAVORITE_LIST_REQUEST';
export const DELETE_PRODUCT_FROM_FAVORITE_LIST_SUCCESS = 'DELETE_PRODUCT_FROM_FAVORITE_LIST_SUCCESS'; 
export const DELETE_PRODUCT_FROM_FAVORITE_LIST_FAILURE = 'DELETE_PRODUCT_FROM_FAVORITE_LIST_FAILURE'; 

export const GET_PRODUCT_PAGINATION_REQUEST = "GET_PRODUCT_PAGINATION_REQUEST";
