export const GET_PRODUCTS_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCTS_FAILURE = "GET_PRODUCT_FAILURE";

export const GET_ALL_BRAND_REQUEST = "GET_ALL_BRAND_REQUEST";
export const GET_ALL_BRAND_SUCCESS = "GET_ALL_BRAND_SUCCESS";
export const GET_ALL_BRAND_FAILURE = "GET_ALL_BRAND_FAILURE";

export const GET_ALL_CATEGORY_REQUEST = "GET_ALL_CATEGORY_REQUEST";
export const GET_ALL_CATEGORY_SUCCESS = "GET_ALL_CATEGORY_SUCCESS";
export const GET_ALL_CATEGORY_FAILURE = "GET_ALL_CATEGORY_FAILURE";

export const GET_SINGLE_PRODUCTS_REQUEST = "GET_SINGLE_PRODUCT_REQUEST";
export const GET_SINGLE_PRODUCTS_SUCCESS = "GET_SINGLE_PRODUCT_SUCCESS";
export const GET_SINGLE_PRODUCTS_FAILURE = "GET_SINGLE_PRODUCT_FAILURE";

export const GET_CATEGORY_COUNT_REQUEST = "GET_CATEGORY_COUNT_REQUEST";
export const GET_CATEGORY_COUNT_SUCCESS = "GET_CATEGORY_COUNT_SUCCESS";
export const GET_CATEGORY_COUNT_FAILURE = "GET_CATEGORY_COUNT_FAILURE";

export const GET_PRODUCT_PAGINATION_REQUEST = "GET_PRODUCT_PAGINATION_REQUEST";
