export const ADD_BRAND_REQUEST = "ADD_BRAND_REQUEST";
export const ADD_BRAND_SUCCESS = "ADD_BRAND_SUCCESS";
export const ADD_BRAND_FAILURE = "ADD_BRAND_FAILURE";

export const DELETE_BRAND_REQUEST = "DELETE_BRAND_REQUEST";
export const DELETE_BRAND_SUCCESS = "DELETE_BRAND_SUCCESS";
export const DELETE_BRAND_FAILURE = "DELETE_BRAND_FAILURE";

export const UPDATE_BRAND_REQUEST = 'UPDATE_BRAND_REQUEST';
export const UPDATE_BRAND_SUCCESS = 'UPDATE_BRAND_SUCCESS';
export const UPDATE_BRAND_FAILURE = 'UPDATE_BRAND_FAILURE';

export const ADD_CATEGORY_REQUEST = "ADD_CATEGORY_REQUEST";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAILURE = "ADD_CATEGORY_FAILURE";

export const DELETE_CATEGORY_REQUEST = "DELETE_CATEGORY_REQUEST";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAILURE = "DELETE_CATEGORY_FAILURE";

export const UPDATE_CATEGORY_REQUEST = 'UPDATE_CATEGORY_REQUEST';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_FAILURE = 'UPDATE_CATEGORY_FAILURE';

export const GET_ALL_PRODUCT_REQUEST = "GET_ALL_PRODUCT_REQUEST";
export const GET_ALL_PRODUCT_SUCCESS = "GET_ALL_PRODUCT_SUCCESS";
export const GET_ALL_PRODUCT_FAILURE = "GET_ALL_PRODUCT_FAILURE";

export const ADD_NEW_PRODUCT_REQUEST = "ADD_NEW_PRODUCT_REQUEST";
export const ADD_NEW_PRODUCT_SUCCESS = "ADD_NEW_PRODUCT_SUCCESS";
export const ADD_NEW_PRODUCT_FAILURE = "ADD_NEW_PRODUCT_FAILURE";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAILURE = "UPDATE_PRODUCT_FAILURE";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILURE = "DELETE_PRODUCT_FAILURE";

export const GET_ALL_USER_REQUEST = "GET_ALL_USER_REQUEST";
export const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS";
export const GET_ALL_USER_FAILURE = "GET_ALL_USER_FAILURE";

export const CHANGE_ROLE_REQUEST = "CHANGE_ROLE_REQUEST";
export const CHANGE_ROLE_SUCCESS = "CHANGE_ROLE_SUCCESS";
export const CHANGE_ROLE_FAILURE = "CHANGE_ROLE_FAILURE";

export const GET_ALL_ORDERS_REQUEST = 'GET_ALL_ORDERS_REQUEST';
export const GET_ALL_ORDERS_SUCCESS = 'GET_ALL_ORDERS_SUCCESS';
export const GET_ALL_ORDERS_FAILURE = 'GET_ALL_ORDERS_FAILURE';

export const UPDATE_ORDER_STATUS_REQUEST = 'UPDATE_ORDER_STATUS_REQUEST'
export const UPDATE_ORDER_STATUS_SUCCESS = 'UPDATE_ORDER_STATUS_SUCCESS'
export const UPDATE_ORDER_STATUS_FAILURE = 'UPDATE_ORDER_STATUS_FAILURE'

export const GET_ANALYTIC_REQUEST = "GET_ANALYTIC_REQUEST";
export const GET_ANALYTIC_SUCCESS = "GET_ANALYTIC_SUCCESS";
export const GET_ANALYTIC_FAILURE = "GET_ANALYTIC_FAILURE";

export const GET_ALL_PERMISSION_REQUEST = "GET_ALL_PERMISSION_REQUEST";
export const GET_ALL_PERMISSION_SUCCESS = "GET_ALL_PERMISSION_SUCCESS";
export const GET_ALL_PERMISSION_FAILURE = "GET_ALL_PERMISSION_FAILURE";

export const GET_ALL_ROLE_REQUEST = "GET_ALL_ROLE_REQUEST";
export const GET_ALL_ROLE_SUCCESS = "GET_ALL_ROLE_SUCCESS";
export const GET_ALL_ROLE_FAILURE = "GET_ALL_ROLE_FAILURE";

export const CREATE_ROLE_REQUEST = "CREATE_ROLE_REQUEST";
export const CREATE_ROLE_SUCCESS = "CREATE_ROLE_SUCCESS";
export const CREATE_ROLE_FAILURE = "CREATE_ROLE_FAILURE";

export const DELETE_ROLE_REQUEST = "DELETE_ROLE_REQUEST";
export const DELETE_ROLE_SUCCESS = "DELETE_ROLE_SUCCESS";
export const DELETE_ROLE_FAILURE = "DELETE_ROLE_FAILURE";

export const CREATE_NEW_COUPCON_REQUEST = "CREATE_NEW_COUPCON_REQUEST"
export const CREATE_NEW_COUPCON_SUCCESS = "CREATE_NEW_COUPCON_SUCCESS"
export const CREATE_NEW_COUPCON_FAILURE = "CREATE_NEW_COUPCON_FAILURE"

export const GET_ALL_COUPCON_REQUEST = "GET_ALL_COUPCON_REQUEST"
export const GET_ALL_COUPCON_SUCCESS = "GET_ALL_COUPCON_SUCCESS"
export const GET_ALL_COUPCON_FAILURE = "GET_ALL_COUPCON_FAILURE"

export const DELETE_COUPCON_REQUEST = "DELETE_COUPCON_REQUEST"
export const DELETE_COUPCON_SUCCESS = "DELETE_COUPCON_SUCCESS"
export const DELETE_COUPCON_FAILURE = "DELETE_COUPCON_FAILURE"

export const UPDATE_COUPCON_REQUEST = "UPDATE_COUPCON_REQUEST"
export const UPDATE_COUPCON_SUCCESS = "UPDATE_COUPCON_SUCCESS"
export const UPDATE_COUPCON_FAILURE = "UPDATE_COUPCON_FAILURE"

export const CREATE_SUB_ADMIN_ACCOUNT_REQUEST = "CREATE_SUB_ADMIN_ACCOUNT_REQUEST"
export const CREATE_SUB_ADMIN_ACCOUNT_SUCCESS = "CREATE_SUB_ADMIN_ACCOUNT_SUCCESS"
export const CREATE_SUB_ADMIN_ACCOUNT_FAILURE = "CREATE_SUB_ADMIN_ACCOUNT_FAILURE"

export const REMOVE_ACCOUNT_REQUEST = "REMOVE_ACCOUNT_REQUEST"
export const REMOVE_ACCOUNT_SUCCESS = "REMOVE_ACCOUNT_SUCCESS"
export const REMOVE_ACCOUNT_FAILURE = "REMOVE_ACCOUNT_FAILURE"

export const EDIT_ACCOUNT_REQUEST = "EDIT_ACCOUNT_REQUEST"
export const EDIT_ACCOUNT_SUCCESS = "EDIT_ACCOUNT_REQUEST"
export const EDIT_ACCOUNT_FAILURE = "EDIT_ACCOUNT_REQUEST"

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST"
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS"
export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE"

export const CHANGE_ACCOUNT_STATUS_REQUEST = "CHANGE_ACCOUNT_STATUS_REQUEST"
export const CHANGE_ACCOUNT_STATUS_SUCCESS = "CHANGE_ACCOUNT_STATUS_SUCCESS"
export const CHANGE_ACCOUNT_STATUS_FAILURE = "CHANGE_ACCOUNT_STATUS_FAILURE"

export const GET_ORDER_BY_ID_REQUEST = "GET_ORDER_BY_ID_REQUEST";
export const GET_ORDER_BY_ID_SUCCESS = "GET_ORDER_BY_ID_SUCCESS";
export const GET_ORDER_BY_ID_FAILURE = "GET_ORDER_BY_ID_FAILURE";
